# Jekyll Config
permalink: none
markdown: kramdown
pygments: true
exclude: [Gemfile,Gemfile.lock,Rakefile,CNAME,README.md]

# Site Variables
github_url: https://github.com/kissmetrics/km-support/blob/gh-pages/

markdown_ext:  markdown,mkdown,mkdn,mkd,md,apibp

permalink: /:categories/:title

# Styling
sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: true